### ISSUE TITLE
java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft

### ISSUE THREAD

**Issue by Sasikaa** [BuildCraft/BuildCraft#2679]
This crash with Buidcraft 7.0.2 beta and Buildcraft Additions 2.1.3

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/29/15 9:20 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:299)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:307)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: buildcraft/core/CreativeTabBuildCraft
	at forestry.pipes.proxy.ProxyPipes.initPropolisPipe(ProxyPipes.java:35)
	at forestry.pipes.proxy.ClientProxyPipes.initPropolisPipe(ClientProxyPipes.java:28)
	at forestry.plugins.PluginPropolisPipe.postInit(PluginPropolisPipe.java:64)
	at forestry.plugins.PluginManager.runPostInit(PluginManager.java:296)
	at forestry.core.ForestryCore.postInit(ForestryCore.java:118)
	at forestry.core.ForestryClient.postInit(ForestryClient.java:41)
	at forestry.Forestry.postInit(Forestry.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:530)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
	... 19 more
Caused by: java.lang.ClassNotFoundException: buildcraft.core.CreativeTabBuildCraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 57 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 331186888 bytes (315 MB) / 777510912 bytes (741 MB) up to 4207738880 bytes (4012 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r28 for 1.7.10
	LaunchWrapper: 41 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: me.guichaguri.betterfps.BetterFpsTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: com.creativemd.minecraftloader.MinecraftTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: redgear.core.asm.GlassAndIceTransformer
          - Transformer: redgear.core.asm.FiniteWaterTransformer
          - Transformer: redgear.core.asm.SafeCactusTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: tterrag.core.common.transform.TTCoreTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: mods.immibis.core.impl.MultiInterfaceClassTransformer
          - Transformer: mods.immibis.core.impl.TraitTransformer
	JVM Flags: 14 total; -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1388 75 mods loaded, 75 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FML{7.10.114.1388} [Forge Mod Loader] (forge-1.7.10-10.13.3.1388-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forge{10.13.3.1388} [Minecraft Forge] (forge-1.7.10-10.13.3.1388-1.7.10-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	betterfps{1.0.0} [BetterFps] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughItems{1.0.4.105} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.105-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IC2{2.2.718-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.718-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	AromaBackup{0.0.0.5} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.104-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bluepower{0.2.928} [Blue Power] (BluePower-1.7.10-0.2.928-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Core{7.0.2} [BuildCraft] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Silicon{7.0.2} [BC Silicon] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Transport{7.0.2} [BC Transport] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Builders{7.0.2} [BC Builders] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Robotics{7.0.2} [BC Robotics] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Energy{7.0.2} [BC Energy] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	BuildCraft|Factory{7.0.2} [BC Factory] (buildcraft-7.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	eureka{3.0.2} [Eureka] (Eureka-1.7.10-3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	bcadditions{2.1.3} [BuildCraft Additions] (BuildcraftAdditions-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CompactSolars{4.4.39.315} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Forestry{3.5.4.13} [Forestry for Minecraft] (forestry_1.7.10-3.5.4.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	IC2NuclearControl{2.2.1a-Yolo} [Nuclear Control 2] (IC2NuclearControl-2.2.1a-Yolo.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	redgear_morebackpacks{2.2.2} [More Backpacks] (More Backpacks-1.7.10-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
	NEIAddons{1.12.5.17} [NEI Addons] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Botany{1.12.5.17} [NEI Addons: Botany] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|Forestry{1.12.5.17} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|CraftingTables{1.12.5.17} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NEIAddons|ExNihilo{1.12.5.17} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.5.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neiintegration{1.0.7} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	NotEnoughCodecs{0.3} [NotEnoughCodecs] (NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	neresources{0.1.0.95} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.95.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	PowerConverters{1.7.10_3.2.0-jenkins.61} [Power Converters] (PowerConverters-1.7.10_3.2.0-jenkins.61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ProjectE{1.7.10-PE1.4.5} [ProjectE] (ProjectE-1.7.10-PE1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	screwdriver{2.0} [Hlestakov's Screwdriver] (screwdriver-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	StorageDrawers{1.7.10-1.3.9} [Storage Drawers] (StorageDrawers-1.7.10-1.3.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ttCore{MC1.7.10-0.1.0-67} [ttCore] (ttCore-MC1.7.10-0.1.0-67.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	Tubestuff{59.0.3} [Tubestuff] (tubestuff-59.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wailaplugins{MC1.7.10-0.0.1-14} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	wawla{1.2.1} [What Are We Looking At] (Wawla-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
	CoFHCore: -[1.7.10]3.0.2-262
	NetherOres: -[1.7.10]2.3.0-12

**Comment by Sasikaa** [comment]
Problem is solved! This is my problem.
Forestry PropolisPipe.
The forestry modules.cfg file modified this line:
    # Adds the apiarist's pipe for beekeeping if apiculture is enabled and BuildCraft 6 is present.
    B:propolis.pipe=true

This set is FALSE and TA-DA! Working perfectly...

**Comment by asiekierka** [comment]
I guess it says BuildCraft *6* for a reason...

**Comment by cocopuffs99** [comment]
+1 for this fix, until the mod owners fix buildcraft compatibility with other mods! now i can play regrowth finally...

thx @Sasikaa !

**Comment by asiekierka** [comment]
No, you should just update BuildCraftCompat and Forestry too.

**Comment by cocopuffs99** [comment]
Updating both to the latest versions, still have the same problem, the only way to fix it is changing the config

**Comment by AEnterprise** [comment]
no you need to have the latest forestry and it will work

**Comment by cocopuffs99** [comment]
Oh k, will try.  Thanks =)
