### ISSUE TITLE
Robots only charge to 20% when "go to home" is true

### ISSUE THREAD

**Issue by chemdork123** [BuildCraft/BuildCraft#3000]
Robot recharging appears to not work properly in BC 7.0.20 when the robots power level is below 20% unless they are working in an area.  The robot will charge only to 20%, then head back home... then shortly go below 20% and go back to the charging station and be locked into this back and forth forever.

This appears to only happen with robots who are set to "go to home", on their way "home", or sitting in "home".  For example, a robot less than 20% when placed onto a docking station that is being given a command "go to home" will seek a power station, fill to 20% and exhibit the same behavior issue.  Robots "working in area" appear to have no problem filling to 100% charge before returning to work.

Is this a bug?

**Comment by asiekierka** [comment]
Yes, this is quite a bug.

**Comment by asiekierka** [comment]
(Also, could not reproduce. At least not on 7.0.21)

**Comment by chemdork123** [comment]
Hm.  I'll try it again on 7.0.21... Happened when the robot was being given the "go to home" action, both with and without a map location marker.

**Comment by hea3ven** [comment]
From only reading the code, it should happen in 7.0.x, it was introduced here https://github.com/BuildCraft/BuildCraft/commit/9ee59473971501be7c3ed231939eba548f72d7e9#diff-4c137d7b470a3782fcdcfb2d8f174d5dL29 . If you re-add the "!(ai instanceof AIRobotRecharge)" condition back to prevent the overriding ai from starting, it should fix it.

**Comment by chemdork123** [comment]
Yeah, it still happens for me in 7.0.21, but seems that this is expected from the code.  Thanks, @hea3ven.

**Comment by asiekierka** [comment]
Thanks, @hea3ven! Fixing it now...

**Comment by asiekierka** [comment]
By the way, nice 3000 GET.
