### ISSUE TITLE
Server crashes upon client connect

### ISSUE THREAD

**Issue by SpartanSamuel** [BuildCraft/BuildCraft#3363]
I recently updated both my server and client with v7.2.7. Now, regardless of if I use 7.2.6 or 7.2.7 my server crashes upon my client connecting. Below are the pastebins of the crash logs. It appears to be something regarding my wooden pipes, but I can't get in the server to take them out.

MC: 1.8.9
Forge: 11.15.1.1855
BC: 7.2.6 / 7.2.7

[Client 7.2.6](http://pastebin.com/SMMTzkzH)
[Server 7.2.6](http://pastebin.com/0tAX3Reh)
[Server 7.2.7](http://pastebin.com/DrHvCBZ2)

**Comment by dj3520** [comment]
Looks to me like it's actually a path marker at -212,69,-13. I'd suggest backing up the world (in case one of the developers here needs to take a look at it more carefully) and using either WorldEdit or MCEdit to remove it.

**Comment by AEnterprise** [comment]
it is a path marker block but for some reason a pipe is editing the data (as if a pipe TE ended up at that location)

**Comment by SpartanSamuel** [comment]
That stinks! Currently, that's- to my knowledge- literally the only pipe we have placed in the world right now. It's a wooden pipe that transfers items from a Blood Magic altar to a chest. I went into MCEdit and removed it, but no dice. Same issue.

[Server 7.2.7 Fix1](http://pastebin.com/1EymXpcQ)
[Client 7.2.7 Fix1](http://pastebin.com/Ay9TWiu4)

**Comment by AEnterprise** [comment]
did you also remove the path marker?

**Comment by laz2727** [comment]
And their TEs.

**Comment by SpartanSamuel** [comment]
Yup! With that coordinate selected, I clicked on all three of the following: Delete Blocks, Delete Entities, and Delete Tile Ticks. What's a path marker and how do I go about removing one?

**Comment by AEnterprise** [comment]
the marker is at -212,69,-13 the block is a path marker but the TE is that of a pipe for some reason, the TE is trying to re-init the block as a pipe for rendering but crashes as there is a marker and not a pipe there

removing the block and TE at -212,69,-13 should fix the crash

**Comment by SpartanSamuel** [comment]
Ah. I can confirm that there was previously a wooden pipe there. I put it there myself. Since then, however, I've removed anything in that location using MCEdit. I'm still crashing.

**Comment by AEnterprise** [comment]
weird, the only other explanation i can think off then is that the TE is somewhere else and somehow using the wrong coords to inialise itself though i am not sure how that could heapen

how heavely is BC used on the server?

**Comment by AEnterprise** [comment]
just noticed your edit (please make new replies, if the edit isn't directy after posting, makes it easier to notice) and now it's a similar crash but with botania.

it seems your world somehow got corrupted, blocks and TE's all over your world don't match anymore, the only thing i know that causes that block remapping by a mod going horribly wrong

**Comment by SpartanSamuel** [comment]
Ooooooo boy. Alright, I'll make a ticket over there and link it here for posterity. If it's alright, please leave this ticket open until it's resolved one way or another. I'll reply with any new discoveries here as well.

**Comment by AEnterprise** [comment]
a ticket over there won't fix it i'm afraid, the crashes are just the symptomes of a corrupt world, your best bet is returning to a backup, if it still crashes go back to the old version you had running and update the mods one by one until it crashes to determine what mod is corrupting the world with it's update

**Comment by SpartanSamuel** [comment]
That's too bad. I know the turkey shoot approach is the most efficient, it's just painful haha. I'll give it a go and report back here when I'm done. I appreciate the advice!

**Comment by SpartanSamuel** [comment]
BuildCraft was updated with a handful of other mods. I reverted back to a previous, backed up world before the updates and began installing them one by one. I still don't know what caused the issue but it's fine now.
