### ISSUE TITLE
Hand Going through blocks

### ISSUE THREAD

**Issue by Callum-Bell** [BuildCraft/BuildCraft#4168]
BuildCraft version:  Latest 1.12.2
Forge version: Latest
Link to crash report or log: 
Singleplayer or multiplayer: MP 
Steps to reproduce: Not sure, just a quarry in a area
Additional information: Hand going through blocks. Triggers when near a quarry (I think this is a buildcraft issue, since thats the only mod in that chunk and it only happens when you are in the area, then it is perma until you leave far away from the Quarry and rejoin, (Then it repeats when going to the quarry

![image](https://user-images.githubusercontent.com/20866724/40194056-1012d3e2-5a01-11e8-92ee-668006333868.png)

**Comment by Callum-Bell** [comment]
^ Was attempting to add tags, yeah i have no idea how

**Comment by AlexIIL** [comment]
This looks similar to a previous one: #3624. Are you using optifine? It's possible that we might be able to do something about it though, so what version of buildcraft and optifine are you using?

Oh only people with write access to a project can modify tags.

**Comment by AlexIIL** [comment]
According to https://optifine.net/downloads 1.12.2 D3 has been released, can you try with that? (Also, can you try without optifine? I'd like to check to see if it is optifine related, as then it's simpler to test...)

**Comment by Callum-Bell** [comment]
If you need any more information i be happy to help

**Comment by AlexIIL** [comment]
Ok, unfortunately I probably won't get around to actually investigating this for a while - although I haven't been able to reproduce this yet from my small amount of testing.

**Comment by Callum-Bell** [comment]
Sorry Alex, my bad. I didnt remove optifine... The issue only happens with optifine, im on (1.12.2 D2)

**Comment by AlexIIL** [comment]
Ah, ok, that simplifies it a bit. I'd like to get more optifine compatibility at *some* point, but it probably won't happen for a while.

**Comment by Starflight164** [comment]
Just to be helpful, I found that if you disable fast render in the optifine settings, your hand will not go through blocks.

**Comment by sergigb2012** [comment]
I also turned the optifine option FAST RENDER: OFF and the bug is aparently fixed

**Comment by Unusual-Danger** [comment]
So does that mean this has been solved after 2 years?

**Comment by gatoborrachon** [comment]
well, i was testing somethings related to EU-MJ Engine mod, and it seems that this bug appears when you see to a Buildcraft tile entity like the engines (from both Buildcraft and EU-MJ Engine), quarry, mining well, etc.
(i want to add that it does not appear with any MJ tranformer from EnergyConverters mod, also, i turned off the fast render but the bug stills )

**Comment by jhaica12** [comment]
I fixed it, You don't need to turn off fast render, all you need to do is go to options>video settings>shaders then on the top right you will see hand depth, set it to 0.5, thank me later.

**Comment by gatoborrachon** [comment]
> options>video settings>shaders then on the top right you will see hand depth

@jhaica12  but that requires a shader right?
